### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by SaifulAzam** [justincdotme/fooCart#1]
ErrorException in Filesystem.php line 75: 
file_put_contents(/c2efa7ff7fc14f470c879645e6842fe3): failed to open stream: Permission denied

**Comment by justincdotme** [comment]
Can you verify that the /storage directory is writeable by the webserver process?

**Comment by SaifulAzam** [comment]
Yes its writeable

**Comment by justincdotme** [comment]
Can you please paste the output of running this command in the installation directory:
`ls -al`

**Comment by SaifulAzam** [comment]
drwxr-xr-x 12 root     www-data   4096 Jul 24 19:10 .
drwxr-xr-x  4 root     root       4096 Jul 24 18:56 ..
drwxr-xr-x 11 root     www-data   4096 Jul 24 18:56 app
-rwxr-xr-x  1 root     www-data   1635 Jul 24 18:56 artisan
drwxr-xr-x  2 root     www-data   4096 Jul 24 18:56 bootstrap
-rwxr-xr-x  1 root     www-data    974 Jul 24 18:56 composer.json
-rwxr-xr-x  1 root     www-data 123968 Jul 24 19:02 composer.lock
drwxr-xr-x  2 root     www-data   4096 Jul 24 18:56 config
drwxr-xr-x  4 root     www-data   4096 Jul 24 18:56 database
-rwxr-xr-x  1 root     www-data    206 Jul 24 20:22 .env
-rwxr-xr-x  1 root     www-data    175 Jul 24 18:56 .env.example
drwxr-xr-x  8 root     www-data   4096 Jul 24 18:56 .git
-rwxr-xr-x  1 root     www-data     35 Jul 24 18:56 .gitignore
-rwxr-xr-x  1 root     www-data   1524 Jul 24 18:56 gulpfile.js
-rwxr-xr-x  1 root     www-data     79 Jul 24 18:56 package.json
-rwxr-xr-x  1 root     www-data     95 Jul 24 18:56 phpspec.yml
-rwxr-xr-x  1 root     www-data    729 Jul 24 18:56 phpunit.xml
drwxr-xr-x  6 root     www-data   4096 Jul 24 18:56 public
-rwxr-xr-x  1 root     www-data   4134 Jul 24 18:56 readme.md
drwxr-xr-x  4 root     www-data   4096 Jul 24 18:56 resources
-rwxr-xr-x  1 root     www-data    561 Jul 24 18:56 server.php
drwxrwxrwx  6 www-data www-data   4096 Jul 24 19:03 storage
drwxr-xr-x  2 root     www-data   4096 Jul 24 18:56 tests
-rwxr-xr-x  1 root     www-data      0 Jul 24 19:10 vagrant
drwxr-xr-x 32 root     www-data   4096 Jul 24 19:02 vendor

**Comment by justincdotme** [comment]
I was able to replicate the issue on my end via fresh clone. The issue was that I apparently left out 3 directories that are supposed to be inside of the storage/framework dir. I've added those directories to the application. Can you run a git pull and confirm if the issue is resolved on your end? You may also need to adjust the permissions on the storage dir again, it and all subdirs should be writeable by the webserver process.

**Comment by SaifulAzam** [comment]
Thanks Its work

**Comment by justincdotme** [comment]
Awesome, thank you for pointing that issue out to me.

**Comment by SaifulAzam** [comment]
I have one more question 
does "bookme" package work with laravel 5.1?

**Comment by justincdotme** [comment]
No, bookMe isn't a Laravel application.
