### ISSUE TITLE
Install Clear Laravel?

### ISSUE THREAD

**Issue by BonBonSlick** [justincdotme/fooCart#2]
I have installed as it says, and i have clear Laravel 5.2 simple page. I checked in your repository, there are no a lot of views etc things. It is clear and embded Laravel starter site, with standard welcome blade =/

**Comment by justincdotme** [comment]
Hello,
It sounds like you have cloned the master branch of this repository. As the readme states: "This is the latest version of the fooCart application and it is currently under development. The old, stable version is now located in the legacy branch." 

I have not yet developed the views (or even the controllers for that matter) for the latest version of this application but if you review the /database and app\Core\Models directories, you will see that this application is already very different than a stock, Laravel 5 installation.
