### ISSUE TITLE
Error Images 

### ISSUE THREAD

**Issue by stylder** [justincdotme/fooCart#4]
:8000/admin/products/images Failed to load resource

**Comment by justincdotme** [comment]
Hello,
I developed the app on a server running Nginx and it is untested using php artisan serve. Can you please post the URI that you were accessing when you encountered the error? Can you also please post any additional steps to reproduce?

**Comment by Haider7856** [comment]
routes folder is not there in  fooCart project

**Comment by justincdotme** [comment]
@Haider7856 That is correct, the routes are located here https://github.com/justincdotme/fooCart/blob/legacy/app/Http/routes.php
